export const STUDENTS = [
  // SECTION A

  {
    id: "STU001",
    name: "Amanpreet",
    legacyKey: "Amanpreet",
    section: "A",
    rollNo: 1,
  },
  {
    id: "STU002",
    name: "Amarjot",
    legacyKey: "Amarjot",
    section: "A",
    rollNo: 2,
  },
  {
    id: "STU003",
    name: "Arshdeep",
    legacyKey: "Arshdeep",
    section: "A",
    rollNo: 3,
  },
  {
    id: "STU004",
    name: "Avneet Baljeet Singh",
    legacyKey: "Avneet Baljeet Singh",
    section: "A",
    rollNo: 4,
  },
  {
    id: "STU005",
    name: "Avneet",
    legacyKey: "Avneet",
    section: "A",
    rollNo: 5,
  },
  {
    id: "STU006",
    name: "Ekamjot",
    legacyKey: "Ekamjot",
    section: "A",
    rollNo: 6,
  },
  {
    id: "STU007",
    name: "Gurleen",
    legacyKey: "Gurleen",
    section: "A",
    rollNo: 7,
  },
  {
    id: "STU008",
    name: "Gursharan",
    legacyKey: "Gursharan",
    section: "A",
    rollNo: 8,
  },
  {
    id: "STU009",
    name: "Harleen",
    legacyKey: "Harleen",
    section: "A",
    rollNo: 9,
  },
  {
    id: "STU010",
    name: "Hina",
    legacyKey: "Hina",
    section: "A",
    rollNo: 10,
  },
  {
    id: "STU011",
    name: "Jaskiran",
    legacyKey: "Jaskiran",
    section: "A",
    rollNo: 11,
  },
  {
    id: "STU012",
    name: "Jaspreet",
    legacyKey: "Jaspreet",
    section: "A",
    rollNo: 12,
  },
  {
    id: "STU013",
    name: "Kamalpreet",
    legacyKey: "Kamalpreet",
    section: "A",
    rollNo: 13,
  },
  {
    id: "STU014",
    name: "Kamla Devi Taranjeet",
    legacyKey: "Kamla Devi Taranjeet",
    section: "A",
    rollNo: 14,
  },
  {
    id: "STU015",
    name: "Kiranpreet",
    legacyKey: "Kiranpreet",
    section: "A",
    rollNo: 15,
  },
  {
    id: "STU016",
    name: "Kiratnoor",
    legacyKey: "Kiratnoor",
    section: "A",
    rollNo: 16,
  },
  {
    id: "STU017",
    name: "Manpreet Kaur",
    legacyKey: "Manpreet Kaur",
    section: "A",
    rollNo: 17,
  },
  {
    id: "STU018",
    name: "Noor Kang",
    legacyKey: "Noor Kang",
    section: "A",
    rollNo: 18,
  },
  {
    id: "STU019",
    name: "Parneet",
    legacyKey: "Parneet",
    section: "A",
    rollNo: 19,
  },
  {
    id: "STU020",
    name: "Prabhjeet",
    legacyKey: "Prabhjeet",
    section: "A",
    rollNo: 20,
  },
  {
    id: "STU021",
    name: "Shaganpreet",
    legacyKey: "Shaganpreet",
    section: "A",
    rollNo: 21,
  },
  {
    id: "STU022",
    name: "Satveer",
    legacyKey: "Satveer",
    section: "A",
    rollNo: 22,
  },
  {
    id: "STU052",
    name: "Shabnam",
    legacyKey: "Shabnam",
    section: "A",
    rollNo: 23,
  },
  {
    id: "STU023",
    name: "Simranjeet",
    legacyKey: "Simranjeet",
    section: "A",
    rollNo: 24,
  },
  {
    id: "STU024",
    name: "Sukhpreet",
    legacyKey: "Sukhpreet",
    section: "A",
    rollNo: 25,
  },

  // SECTION B

  {
    id: "STU025",
    name: "Gurkirat",
    legacyKey: "Gurkirat",
    section: "B",
    rollNo: 1,
  },
  {
    id: "STU026",
    name: "Gurleen Prem Singh",
    legacyKey: "Gurleen Prem Singh",
    section: "B",
    rollNo: 2,
  },
  {
    id: "STU027",
    name: "Harmandeep",
    legacyKey: "Harmandeep",
    section: "B",
    rollNo: 3,
  },
  {
    id: "STU028",
    name: "Jashandeep",
    legacyKey: "Jashandeep",
    section: "B",
    rollNo: 4,
  },
  {
    id: "STU029",
    name: "Jasleen",
    legacyKey: "Jasleen",
    section: "B",
    rollNo: 5,
  },
  {
    id: "STU030",
    name: "Nihalika",
    legacyKey: "Nihalika",
    section: "B",
    rollNo: 6,
  },
  {
    id: "STU031",
    name: "Anmol",
    legacyKey: "Anmol",
    section: "B",
    rollNo: 7,
  },
  {
    id: "STU032",
    name: "Gagandeep",
    legacyKey: "Gagandeep",
    section: "B",
    rollNo: 8,
  },
  {
    id: "STU033",
    name: "Gauri",
    legacyKey: "Gauri",
    section: "B",
    rollNo: 9,
  },
  {
    id: "STU034",
    name: "Mahakpreet",
    legacyKey: "Mahakpreet",
    section: "B",
    rollNo: 10,
  },
  {
    id: "STU035",
    name: "Nancy",
    legacyKey: "Nancy",
    section: "B",
    rollNo: 11,
  },
  {
    id: "STU036",
    name: "Navjot",
    legacyKey: "Navjot",
    section: "B",
    rollNo: 12,
  },
  {
    id: "STU037",
    name: "Sukhman",
    legacyKey: "Sukhman",
    section: "B",
    rollNo: 13,
  },
  {
    id: "STU038",
    name: "Sukhmandeep",
    legacyKey: "Sukhmandeep",
    section: "B",
    rollNo: 14,
  },
  {
    id: "STU039",
    name: "Taranpreet",
    legacyKey: "Taranpreet",
    section: "B",
    rollNo: 15,
  },
  {
    id: "STU040",
    name: "Harnoor",
    legacyKey: "Harnoor",
    section: "B",
    rollNo: 16,
  },
  {
    id: "STU041",
    name: "Simarjeet",
    legacyKey: "Simarjeet",
    section: "B",
    rollNo: 17,
  },
  {
    id: "STU042",
    name: "Sukhjot Saidpura",
    legacyKey: "Sukhjot Saidpura",
    section: "B",
    rollNo: 18,
  },
  {
    id: "STU043",
    name: "Tanveer",
    legacyKey: "Tanveer",
    section: "B",
    rollNo: 19,
  },
  {
    id: "STU044",
    name: "Rehmat Preet",
    legacyKey: "Rehmat Preet",
    section: "B",
    rollNo: 20,
  },
  {
    id: "STU045",
    name: "Khushpreet",
    legacyKey: "Khushpreet",
    section: "B",
    rollNo: 21,
  },
  {
    id: "STU046",
    name: "Gagan Preet",
    legacyKey: "Gagan Preet",
    section: "B",
    rollNo: 22,
  },
  {
    id: "STU047",
    name: "Sehajdeep",
    legacyKey: "Sehajdeep",
    section: "B",
    rollNo: 23,
  },
  {
    id: "STU048",
    name: "Rishu",
    legacyKey: "Rishu",
    section: "B",
    rollNo: 24,
  },
  {
    id: "STU049",
    name: "Amritpal Kaur",
    legacyKey: "Amritpal Kaur",
    section: "B",
    rollNo: 25,
  },
  {
    id: "STU050",
    name: "Jasleen Raya",
    legacyKey: "Jasleen Raya",
    section: "B",
    rollNo: 26,
  },
  {
    id: "STU051",
    name: "Manpreet Raya",
    legacyKey: "Manpreet Raya",
    section: "B",
    rollNo: 27,
  },
];