export const LEGACY_STUDENTS = [
  "Gurkirat",
  "Gurleen",
  "Gurleen Prem Singh",
  "Harleen",
  "Harmandeep",
  "Jashandeep",
  "Jaskiran",
  "Jasleen",
  "Jaspreet",
  "Gursharan",
  "Manpreet Kaur",
  "Nihalika",
  "Amanpreet",
  "Amarjot",
  "Anmol",
  "Avneet Baljeet Singh",
  "Avneet",
  "Gagandeep",
  "Gauri",
  "Kamalpreet",
  "Kamla Devi Taranjeet",
  "Kiranpreet",
  "Kiratnoor",
  "Mahakpreet",
  "Nancy",
  "Navjot",
  "Parneet",
  "Prabhjeet",
  "Satveer",
  "Shaganpreet",
  "Simarjeet",
  "Sukhman",
  "Sukhmandeep",
  "Sukhpreet",
  "Taranpreet",
  "Harnoor",
  "Noor Kang",
  "Simranjeet",
  "Sukhjot Saidpura",
  "Tanveer",
  "Rehmat Preet",
  "Arshdeep",
  "Khushpreet",
  "Gagan Preet",
  "Sehajdeep",
  "Ekamjot",
  "Rishu",
  "Amritpal Kaur",
  "Jasleen Raya",
  "Manpreet Raya",
];
