export const STUDENTS = [
  "Gurkirat",
  "Gurleen",
  "Gurleen Prem Singh",
  "Harleen",
  "Harmandeep",
  "Jashandeep",
  "Jaskiran",
  "Jasleen",
  "Jasmeen",
  "Jaspreet",
  "Gursharan",
  "Manpreet Kaur",
  "Nihalika",
  "Amanpreet",
  "Amarjot",
  "Anmol",
  "Avneet Baljeet Singh",
  "Avneet",
  "Gagandeep",
  "Gauri",
  "Kamalpreet",
  "Kamla Devi Taranjeet",
  "Kiranpreet",
  "Kiratnoor",
  "Mahakpreet",
  "Nancy",
  "Navjot",
  "Parneet",
  "Prabhjeet",
  "Satveer",
  "Shaganpreet",
  "Simarjeet",
  "Sukhman",
  "Sukhmandeep",
  "Sukhpreet",
  "Taranpreet",
  "Harnoor",
  "Noor Kang",
  "Simranjeet",
  "Sukhjot Saidpura",
  "Tanyeer",
  "Bittu Singh",
  "Manjeet Singh",
  "Sandeep",
];